### ISSUE TITLE
Figure 1

### ISSUE THREAD

**Issue by geahaad** [ncomerci/Master-Thesis#6]
Is that really helpful? First its outdated as soon as you snapshot it, second - whats the value of having that in? Nor is it "scientific"

Perhaps better to have a research paper of a consulting firm quoted, with figures and diagrams that go beyond market cap.
What industries are applying crypto, what countries, what companies.... what is the estimated market size for each segment, etc. etc.

**Comment by ncomerci** [comment]
How about using and referencing some of the results of "Deloitte's 2021 Global Blockchain Survey"? 

https://www2.deloitte.com/content/dam/insights/articles/US144337_Blockchain-survey/DI_Blockchain-survey.pdf

They show how financial companies use and envision the future of digital assets based on blockchain

**Comment by geahaad** [comment]
> How about using and referencing some of the results of "Deloitte's 2021 Global Blockchain Survey"?
> 
> https://www2.deloitte.com/content/dam/insights/articles/US144337_Blockchain-survey/DI_Blockchain-survey.pdf
> 
> They show how financial companies use and envision the future of digital assets based on blockchain

Yes excately, that's the type of material that I expected. Deloitte (though a fierce competitor of ours ;-) ) does a good job analysing the broader ecosystem. Those surveys are great to cite.
